token:
  expiration_time: 864000000
  secret: user_token_native_application_changed
spring:
  rabbitmq:
    host: '{cipher}AQAXicvrNbe9uj9EcrSgrenWGxfm7UoSnwQ/ve920X2c8Q9QS+bhDiXfySakO/W1LS6s1BZlI9PCx/8EF6NJugh63wj9vy2t97bkh2nmF7MjTNks0vKgjZbTeeeVgWceVdt7WyWccSPLjyZT6F72Xf7lw/KnpqtSLresK31Mnl78fyfHjy2ltar4XBR3eyToBF1+RgkBy6qgKc57sAyGAN+rS0yPKCU6GwMRtEA/4h9djtlSkswqqU9ftW6rma6CZvHu5ZGF35cH2XME2lDbS7kvFAczeuk2plVpzq7b2OFhSnW9DZC3QXl2XWQFRSSaVevM+Z0rZaZUqpZTFnXfhi9riBCP4eBSGNZB8/lK3sxUFtxIt3xHdl9fXFKO4tDKiINogKnNWPZi0gYkLu5EaOBA'
    port: 5672
    username: '{cipher}AQA9l9Y4N4/oeM1ZMPN9QKVns7TeBoytPBCoYmNfGnw0lpq1fEX0T35QDdCFGYFYAIVh09soZncSb3A5PYe6zHWkBfUomfOTbpgIRKNj8M8a9z2dp6dO+PvapSpiLeotW/MuDOlOdYARbvQJYrlzBw56b3WE2pa37wUoea1ukrbE9vL4fTFt0FbtLXVvd/HWH+BbiKD9jVHcqtfVY/CZOu9uRTgd6iUSaZhH+ZMEi884MRm4Zzdbe4Li3+YggJG8PPH+uTN2FJSM3/ey6zdoHD98xaI1C3H42r1QMi61FUvugU3KbVujpQN4yLwyQMyybbzlKxX7g0EhVoVpI2nqfegyrA5fCbYE2hNTTEPvsM9qgSw95Iz69/LQiApLM1NYSYM='
    password: '{cipher}AQAMtkJS6vStQ+pdA0oXKa7ruume4uap3ftUiVMDTHOwACX5qpCH3JCDw0CXKlN1fC1hmJPC+IQfsV2ORzuKQ346LWf0DSaLDhlQGoEPwWDWyRME8axhZ/1EoR526fAXyMUGbHvDMuQvKXqxDLN4b/dLkeejNHOmO5Y6s0mnQ06CvvKWwxZRbEC3tf0/KbC0hmdLrxs6/V3EBbD99TGeJClm/ZeKEijONtPv8bKr2iodGMXxti6Fw7JT3IAYvT0s9WCWUfztXBuzcz+x9w3Q5CiiiYt+QaVuxqYvGWWHEivXbqyEoiYSnI3qnjj3ppr2jUhx8cl+/c6cmLX63w7/5bhVcEsXvIkrlkzsteHXSwFOBWlgCThOCDzqqA7dB0kZ0ZE='
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: '{cipher}AQBK4hxdfL9Lbza0LPaMwoxbQhUF0C/ANxPJ35WnSG3lffBd2oHgi1JE85DTjc5uJ2iumxRKrgAWQcvKUOuu6S5q0yG2FONcIItAxdRhbLH+VqM7vC8/NEyfQ6p9RrYPzR3Wowmg0Tl/9Uhvc3kJaW13z/FAme9pXXP6lc/vfvpVK7L7Bxx3pd+YWvdlEl4ZfeqrXjEWILOjVHSQHSBcNREFiNGBKqHdITbATXDXIYVvYjNFrKtvaD4I6uyx/66win40u28ixAGJrXZgq83/RfTQia5NG+mN/BgCHubo6Brz3OUbYVWZgfxalT/cGIjGRs/zWaK0ONFaVtysPk8N7AQViPN1rP5XQtqV1mitmHEtg+iB8abCfeflGquQnHE+N8U='
    password:

order_service:
  url:  http://ORDER_SERVICE/order-service/%s/orders
  exception:
    order_is_empty: User's order is empty.
gateway:
  ip: 192.168.0.8